"""Import generated art into the game.

Reads the art contract in D:\\projects\\AshenSanctum-art\\sheets\\manifest.json (written by
the art repo's tools/pack.py), converts every PNG into a raw pixel blob in assets/art/, and
writes src/art_gen.rs, which embeds the blobs with include_bytes! so the game (desktop and
handheld) stays a single executable.

Blob format: u32 width, u32 height (little endian), then width*height u32 pixels
as 0xAARRGGBB (0 = transparent).

Usage (from the repo root, Windows or WSL):  python scripts/import_art.py [art_dir]
Anything missing from the manifest keeps its code-drawn fallback.
"""
import json
import struct
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"D:\projects\AshenSanctum-art")
if not ART.exists():
    ART = Path("/mnt/d/projects/AshenSanctum-art")
SHEETS = ART / "sheets"
OUT = ROOT / "assets" / "art"
GEN = ROOT / "src" / "art_gen.rs"


def blob(src: Path, dest: Path):
    im = Image.open(src).convert("RGBA")
    data = bytearray(struct.pack("<II", im.width, im.height))
    raw = im.tobytes()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        data += struct.pack("<I", 0 if a < 128 else (0xFF000000 | (r << 16) | (g << 8) | b))
    dest.write_bytes(data)


def main():
    man = json.loads((SHEETS / "manifest.json").read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.bin"):
        old.unlink()
    lines = ["// @generated by scripts/import_art.py -- do not edit by hand.",
             "use crate::art::{AnimDef, CharDef, TileDef};", "", "pub static CHARS: &[CharDef] = &["]
    for c in man["chars"]:
        blob(SHEETS / c["file"], OUT / f"{c['name']}.bin")
        anims = ", ".join(
            f'AnimDef {{ name: {json.dumps(a["name"])}, row: {a["row"]}, frames: {a["frames"]}, fps: {a["fps"]} }}'
            for a in c["anims"])
        lines.append(
            f'    CharDef {{ name: {json.dumps(c["name"])}, cell: ({c["cell"][0]}, {c["cell"][1]}), '
            f'anchor: ({c["anchor"][0]}, {c["anchor"][1]}), '
            f'data: include_bytes!("../assets/art/{c["name"]}.bin"), anims: &[{anims}] }},')
        print("char", c["name"], c["cell"], [a["name"] for a in c["anims"]])
    lines += ["];", "", "pub static TILES: &[TileDef] = &["]
    for t in man["tiles"]:
        blob(SHEETS / t["file"], OUT / f"tile_{t['name']}.bin")
        lines.append(
            f'    TileDef {{ name: {json.dumps(t["name"])}, anchor: ({t["anchor"][0]}, {t["anchor"][1]}), '
            f'data: include_bytes!("../assets/art/tile_{t["name"]}.bin") }},')
        print("tile", t["name"])
    lines += ["];", ""]
    GEN.write_text("\n".join(lines))
    print("wrote", GEN)


if __name__ == "__main__":
    main()
