// @generated by scripts/import_art.py -- do not edit by hand.
use crate::art::{AnimDef, CharDef, ItemDef, TileDef};

pub static CHARS: &[CharDef] = &[
    CharDef { name: "mage", cell: (68, 70), anchor: (23, 53), data: include_bytes!("../assets/art/mage.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 10 }, AnimDef { name: "cast", row: 16, frames: 6, fps: 16 }] },
    CharDef { name: "zombie", cell: (44, 50), anchor: (22, 44), data: include_bytes!("../assets/art/zombie.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 7 }, AnimDef { name: "attack", row: 16, frames: 6, fps: 12 }] },
    CharDef { name: "skeleton", cell: (51, 51), anchor: (26, 46), data: include_bytes!("../assets/art/skeleton.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 10 }, AnimDef { name: "attack", row: 16, frames: 6, fps: 14 }] },
    CharDef { name: "wolf", cell: (73, 55), anchor: (31, 39), data: include_bytes!("../assets/art/wolf.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 12 }, AnimDef { name: "attack", row: 16, frames: 6, fps: 14 }] },
    CharDef { name: "imp", cell: (42, 40), anchor: (19, 36), data: include_bytes!("../assets/art/imp.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 12 }, AnimDef { name: "attack", row: 16, frames: 6, fps: 14 }] },
    CharDef { name: "archer", cell: (58, 48), anchor: (27, 43), data: include_bytes!("../assets/art/archer.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 10 }, AnimDef { name: "attack", row: 16, frames: 6, fps: 12 }] },
    CharDef { name: "npc_elder", cell: (22, 49), anchor: (11, 42), data: include_bytes!("../assets/art/npc_elder.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "npc_merchant", cell: (20, 46), anchor: (10, 41), data: include_bytes!("../assets/art/npc_merchant.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "npc_healer", cell: (22, 45), anchor: (10, 40), data: include_bytes!("../assets/art/npc_healer.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "npc_guard", cell: (27, 57), anchor: (14, 51), data: include_bytes!("../assets/art/npc_guard.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "npc_villager", cell: (22, 48), anchor: (11, 43), data: include_bytes!("../assets/art/npc_villager.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "boss_bone", cell: (63, 85), anchor: (28, 78), data: include_bytes!("../assets/art/boss_bone.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "boss_plague", cell: (32, 80), anchor: (16, 72), data: include_bytes!("../assets/art/boss_plague.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "boss_hex", cell: (43, 76), anchor: (19, 70), data: include_bytes!("../assets/art/boss_hex.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "boss_ashking", cell: (59, 116), anchor: (29, 110), data: include_bytes!("../assets/art/boss_ashking.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
];

pub static TILES: &[TileDef] = &[
    TileDef { name: "floor_stone1", anchor: (16, 8), data: include_bytes!("../assets/art/tile_floor_stone1.bin") },
    TileDef { name: "floor_stone2", anchor: (16, 8), data: include_bytes!("../assets/art/tile_floor_stone2.bin") },
    TileDef { name: "grass1", anchor: (16, 8), data: include_bytes!("../assets/art/tile_grass1.bin") },
    TileDef { name: "grass2", anchor: (16, 8), data: include_bytes!("../assets/art/tile_grass2.bin") },
    TileDef { name: "dirt1", anchor: (16, 8), data: include_bytes!("../assets/art/tile_dirt1.bin") },
    TileDef { name: "road1", anchor: (16, 8), data: include_bytes!("../assets/art/tile_road1.bin") },
    TileDef { name: "wall", anchor: (16, 56), data: include_bytes!("../assets/art/tile_wall.bin") },
    TileDef { name: "palisade", anchor: (16, 40), data: include_bytes!("../assets/art/tile_palisade.bin") },
];

pub static ITEMS: &[ItemDef] = &[
    ItemDef { name: "food_apple", data: include_bytes!("../assets/art/item_food_apple.bin") },
    ItemDef { name: "food_bread", data: include_bytes!("../assets/art/item_food_bread.bin") },
    ItemDef { name: "food_roast", data: include_bytes!("../assets/art/item_food_roast.bin") },
    ItemDef { name: "seal", data: include_bytes!("../assets/art/item_seal.bin") },
    ItemDef { name: "tree_oak", data: include_bytes!("../assets/art/item_tree_oak.bin") },
    ItemDef { name: "tree_pine", data: include_bytes!("../assets/art/item_tree_pine.bin") },
    ItemDef { name: "tree_dead", data: include_bytes!("../assets/art/item_tree_dead.bin") },
    ItemDef { name: "rock1", data: include_bytes!("../assets/art/item_rock1.bin") },
    ItemDef { name: "bush1", data: include_bytes!("../assets/art/item_bush1.bin") },
    ItemDef { name: "house1", data: include_bytes!("../assets/art/item_house1.bin") },
    ItemDef { name: "house2", data: include_bytes!("../assets/art/item_house2.bin") },
    ItemDef { name: "tent1", data: include_bytes!("../assets/art/item_tent1.bin") },
    ItemDef { name: "campfire", data: include_bytes!("../assets/art/item_campfire.bin") },
    ItemDef { name: "well", data: include_bytes!("../assets/art/item_well.bin") },
    ItemDef { name: "ent_crypt", data: include_bytes!("../assets/art/item_ent_crypt.bin") },
    ItemDef { name: "ent_warrens", data: include_bytes!("../assets/art/item_ent_warrens.bin") },
    ItemDef { name: "ent_catacombs", data: include_bytes!("../assets/art/item_ent_catacombs.bin") },
    ItemDef { name: "ent_sanctum", data: include_bytes!("../assets/art/item_ent_sanctum.bin") },
    ItemDef { name: "stairs_down", data: include_bytes!("../assets/art/item_stairs_down.bin") },
    ItemDef { name: "stairs_up", data: include_bytes!("../assets/art/item_stairs_up.bin") },
];
