// @generated by scripts/import_art.py -- do not edit by hand.
use crate::art::{AnimDef, CharDef, TileDef};

pub static CHARS: &[CharDef] = &[
    CharDef { name: "mage", cell: (41, 68), anchor: (13, 53), data: include_bytes!("../assets/art/mage.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }, AnimDef { name: "walk", row: 8, frames: 6, fps: 10 }] },
    CharDef { name: "zombie", cell: (20, 47), anchor: (10, 41), data: include_bytes!("../assets/art/zombie.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
    CharDef { name: "skeleton", cell: (31, 45), anchor: (16, 40), data: include_bytes!("../assets/art/skeleton.bin"), anims: &[AnimDef { name: "idle", row: 0, frames: 1, fps: 1 }] },
];

pub static TILES: &[TileDef] = &[
    TileDef { name: "floor_stone1", anchor: (16, 8), data: include_bytes!("../assets/art/tile_floor_stone1.bin") },
    TileDef { name: "floor_stone2", anchor: (16, 8), data: include_bytes!("../assets/art/tile_floor_stone2.bin") },
    TileDef { name: "wall", anchor: (16, 56), data: include_bytes!("../assets/art/tile_wall.bin") },
];
