// Generated by `ashensanctum --export-catalog` (src/levels.rs catalog_js). Don't edit by hand.
window.CATALOG = {
  "dungeons": [
    {
      "act": 0,
      "boss": "boss_bone",
      "floors": 2,
      "name": "THE BONE CRYPT",
      "slug": "bone_crypt",
      "theme": "crypt",
      "tier": 1.0
    },
    {
      "act": 0,
      "boss": "boss_plague",
      "floors": 2,
      "name": "THE ROTTING WARRENS",
      "slug": "rotting_warrens",
      "theme": "warrens",
      "tier": 1.600000023841858
    },
    {
      "act": 0,
      "boss": "boss_hex",
      "floors": 3,
      "name": "THE HEXED CATACOMBS",
      "slug": "hexed_catacombs",
      "theme": "catacombs",
      "tier": 2.299999952316284
    },
    {
      "act": 0,
      "boss": "boss_ashking",
      "floors": 3,
      "name": "THE ASHEN SANCTUM",
      "slug": "ashen_sanctum",
      "theme": "sanctum",
      "tier": 3.200000047683716
    },
    {
      "act": 1,
      "boss": "boss_giant",
      "floors": 2,
      "name": "THE FROZEN MINES",
      "slug": "frozen_mines",
      "theme": "mines",
      "tier": 3.799999952316284
    },
    {
      "act": 1,
      "boss": "boss_yeti",
      "floors": 2,
      "name": "THE HOWLING CAVES",
      "slug": "howling_caves",
      "theme": "icecaves",
      "tier": 4.199999809265137
    },
    {
      "act": 1,
      "boss": "boss_witch",
      "floors": 3,
      "name": "THE RIME TEMPLE",
      "slug": "rime_temple",
      "theme": "rime",
      "tier": 4.599999904632568
    },
    {
      "act": 1,
      "boss": "boss_dragon",
      "floors": 3,
      "name": "THE GLACIER'S HEART",
      "slug": "glaciers_heart",
      "theme": "glacier",
      "tier": 5.199999809265137
    },
    {
      "act": 2,
      "boss": "boss_ossric",
      "floors": 2,
      "name": "THE SUNKEN CHAPEL",
      "slug": "sunken_chapel",
      "theme": "chapel",
      "tier": 5.800000190734863
    },
    {
      "act": 2,
      "boss": "boss_grimhilde",
      "floors": 2,
      "name": "THE GALLOWS CATACOMBS",
      "slug": "gallows_catacombs",
      "theme": "gallows",
      "tier": 6.199999809265137
    },
    {
      "act": 2,
      "boss": "boss_malgrave",
      "floors": 3,
      "name": "THE BARROW OF KNIGHTS",
      "slug": "barrow_of_knights",
      "theme": "barrow",
      "tier": 6.599999904632568
    },
    {
      "act": 2,
      "boss": "boss_vardak",
      "floors": 3,
      "name": "CASTLE VARDAK",
      "slug": "castle_vardak",
      "theme": "castle",
      "tier": 7.199999809265137
    },
    {
      "act": 3,
      "boss": "boss_forgemother",
      "floors": 2,
      "name": "THE FOUNDRY OF SOULS",
      "slug": "foundry_of_souls",
      "theme": "foundry",
      "tier": 7.800000190734863
    },
    {
      "act": 3,
      "boss": "boss_cantor",
      "floors": 2,
      "name": "THE CHOIR ENGINE",
      "slug": "choir_engine",
      "theme": "choir",
      "tier": 8.199999809265137
    },
    {
      "act": 3,
      "boss": "boss_archivist",
      "floors": 3,
      "name": "THE ARCHIVE OF GEARS",
      "slug": "archive_of_gears",
      "theme": "archive",
      "tier": 8.600000381469727
    },
    {
      "act": 3,
      "boss": "boss_clockmaker",
      "floors": 3,
      "name": "THE HEART OF THE CLOCK",
      "slug": "heart_of_the_clock",
      "theme": "clock",
      "tier": 9.199999809265137
    },
    {
      "act": 4,
      "boss": "boss_dregmoor",
      "floors": 2,
      "name": "THE WRECK OF THE SOVEREIGN",
      "slug": "wreck_of_the_sovereign",
      "theme": "wreck",
      "tier": 10.199999809265137
    },
    {
      "act": 4,
      "boss": "boss_nacre",
      "floors": 2,
      "name": "THE CORAL CATHEDRAL",
      "slug": "coral_cathedral",
      "theme": "reef",
      "tier": 10.600000381469727
    },
    {
      "act": 4,
      "boss": "boss_angler",
      "floors": 3,
      "name": "THE MIDNIGHT TRENCH",
      "slug": "midnight_trench",
      "theme": "trench",
      "tier": 11.0
    },
    {
      "act": 4,
      "boss": "boss_leviathan",
      "floors": 3,
      "name": "THE DROWNED SANCTUM",
      "slug": "drowned_sanctum",
      "theme": "drowned",
      "tier": 11.600000381469727
    },
    {
      "act": 5,
      "boss": "boss_vael",
      "floors": 2,
      "name": "THE BROKEN CHOIR",
      "slug": "broken_choir",
      "theme": "seraph",
      "tier": 12.199999809265137
    },
    {
      "act": 5,
      "boss": "boss_tempest",
      "floors": 2,
      "name": "THE STORM SPIRE",
      "slug": "storm_spire",
      "theme": "spire",
      "tier": 12.600000381469727
    },
    {
      "act": 5,
      "boss": "boss_ophan",
      "floors": 3,
      "name": "THE WHEEL OF EYES",
      "slug": "wheel_of_eyes",
      "theme": "wheel",
      "tier": 13.0
    },
    {
      "act": 5,
      "boss": "boss_solanthos",
      "floors": 3,
      "name": "THE TRUE SANCTUM",
      "slug": "true_sanctum",
      "theme": "zenith",
      "tier": 13.600000381469727
    },
    {
      "act": 0,
      "boss": "boss_wellwitch",
      "floors": 2,
      "name": "THE CHARNEL WELL",
      "slug": "charnel_well",
      "theme": "warrens",
      "tier": 1.899999976158142
    },
    {
      "act": 0,
      "boss": "boss_firewyrm",
      "floors": 1,
      "name": "THE WYRM'S HOARD",
      "slug": "wyrms_hoard",
      "theme": "sanctum",
      "tier": 2.200000047683716
    },
    {
      "act": 1,
      "boss": "boss_hrolf",
      "floors": 2,
      "name": "THE ICEBOUND LONGSHIP",
      "slug": "icebound_longship",
      "theme": "wreck",
      "tier": 4.400000095367432
    }
  ],
  "lands": {
    "area:0:1": {
      "act": 0,
      "doors": [
        24
      ],
      "exits": [
        [
          0,
          "HOLLOWMERE"
        ],
        [
          2,
          "THE BARROW FIELDS"
        ],
        [
          7,
          "SHEPHERD'S VALE"
        ]
      ],
      "name": "THE ASHLANDS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "overworld",
      "tier": 1.0,
      "town": false
    },
    "area:0:2": {
      "act": 0,
      "doors": [
        0
      ],
      "exits": [
        [
          1,
          "THE ASHLANDS"
        ],
        [
          3,
          "THE ROTWOOD"
        ],
        [
          8,
          "SKRAT'S GULCH"
        ]
      ],
      "name": "THE BARROW FIELDS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "overworld",
      "tier": 1.2999999523162842,
      "town": false
    },
    "area:0:3": {
      "act": 0,
      "doors": [
        1
      ],
      "exits": [
        [
          2,
          "THE BARROW FIELDS"
        ],
        [
          4,
          "THE CINDER HILLS"
        ]
      ],
      "name": "THE ROTWOOD",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "overworld",
      "tier": 1.7000000476837158,
      "town": false
    },
    "area:0:4": {
      "act": 0,
      "doors": [
        2
      ],
      "exits": [
        [
          3,
          "THE ROTWOOD"
        ],
        [
          5,
          "THE CINDER WASTE"
        ],
        [
          9,
          "EMBERPEAK PASS"
        ]
      ],
      "name": "THE CINDER HILLS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "overworld",
      "tier": 2.0999999046325684,
      "town": false
    },
    "area:0:5": {
      "act": 0,
      "doors": [],
      "exits": [
        [
          4,
          "THE CINDER HILLS"
        ],
        [
          6,
          "THE ASHEN STEPPE"
        ]
      ],
      "name": "THE CINDER WASTE",
      "passes": [],
      "shops": [],
      "size": [
        112,
        80
      ],
      "story": null,
      "theme": "overworld",
      "tier": 2.5999999046325684,
      "town": false
    },
    "area:0:6": {
      "act": 0,
      "doors": [
        3
      ],
      "exits": [
        [
          5,
          "THE CINDER WASTE"
        ]
      ],
      "name": "THE ASHEN STEPPE",
      "passes": [
        "pass1"
      ],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "overworld",
      "tier": 3.0,
      "town": false
    },
    "area:0:7": {
      "act": 0,
      "doors": [],
      "exits": [
        [
          1,
          "THE ASHLANDS"
        ]
      ],
      "name": "SHEPHERD'S VALE",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "overworld",
      "tier": 1.2000000476837158,
      "town": false
    },
    "area:0:8": {
      "act": 0,
      "doors": [],
      "exits": [
        [
          2,
          "THE BARROW FIELDS"
        ]
      ],
      "name": "SKRAT'S GULCH",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "overworld",
      "tier": 1.5,
      "town": false
    },
    "area:0:9": {
      "act": 0,
      "doors": [
        25
      ],
      "exits": [
        [
          4,
          "THE CINDER HILLS"
        ]
      ],
      "name": "EMBERPEAK PASS",
      "passes": [],
      "shops": [],
      "size": [
        72,
        80
      ],
      "story": null,
      "theme": "overworld",
      "tier": 2.0,
      "town": false
    },
    "area:1:1": {
      "act": 1,
      "doors": [
        4
      ],
      "exits": [
        [
          0,
          "KALDHOLM"
        ],
        [
          2,
          "THE HOWLING TUNDRA"
        ],
        [
          6,
          "THE RAIDERS' FJORD"
        ]
      ],
      "name": "THE FROZEN SHORE",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "tundra",
      "tier": 3.5999999046325684,
      "town": false
    },
    "area:1:2": {
      "act": 1,
      "doors": [
        5
      ],
      "exits": [
        [
          1,
          "THE FROZEN SHORE"
        ],
        [
          3,
          "THE RIME WOODS"
        ]
      ],
      "name": "THE HOWLING TUNDRA",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "tundra",
      "tier": 3.9000000953674316,
      "town": false
    },
    "area:1:3": {
      "act": 1,
      "doors": [
        6
      ],
      "exits": [
        [
          2,
          "THE HOWLING TUNDRA"
        ],
        [
          4,
          "THE WHITE WASTE"
        ]
      ],
      "name": "THE RIME WOODS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "tundra",
      "tier": 4.300000190734863,
      "town": false
    },
    "area:1:4": {
      "act": 1,
      "doors": [],
      "exits": [
        [
          3,
          "THE RIME WOODS"
        ],
        [
          5,
          "THE GLACIER'S EDGE"
        ]
      ],
      "name": "THE WHITE WASTE",
      "passes": [],
      "shops": [],
      "size": [
        112,
        80
      ],
      "story": null,
      "theme": "tundra",
      "tier": 4.699999809265137,
      "town": false
    },
    "area:1:5": {
      "act": 1,
      "doors": [
        7
      ],
      "exits": [
        [
          4,
          "THE WHITE WASTE"
        ]
      ],
      "name": "THE GLACIER'S EDGE",
      "passes": [
        "pass2"
      ],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "tundra",
      "tier": 5.0,
      "town": false
    },
    "area:1:6": {
      "act": 1,
      "doors": [
        26
      ],
      "exits": [
        [
          1,
          "THE FROZEN SHORE"
        ]
      ],
      "name": "THE RAIDERS' FJORD",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "tundra",
      "tier": 4.0,
      "town": false
    },
    "area:2:1": {
      "act": 2,
      "doors": [
        8
      ],
      "exits": [
        [
          0,
          "MOURNHOLD"
        ],
        [
          2,
          "THE GALLOWS MOOR"
        ],
        [
          6,
          "THE WITCH'S BOG"
        ]
      ],
      "name": "THE BLIGHTED FIELDS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 5.599999904632568,
      "town": false
    },
    "area:2:2": {
      "act": 2,
      "doors": [
        9
      ],
      "exits": [
        [
          1,
          "THE BLIGHTED FIELDS"
        ],
        [
          3,
          "THE HOLLOW WOOD"
        ]
      ],
      "name": "THE GALLOWS MOOR",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 6.0,
      "town": false
    },
    "area:2:3": {
      "act": 2,
      "doors": [],
      "exits": [
        [
          2,
          "THE GALLOWS MOOR"
        ],
        [
          4,
          "THE BARROW HILLS"
        ]
      ],
      "name": "THE HOLLOW WOOD",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 6.400000095367432,
      "town": false
    },
    "area:2:4": {
      "act": 2,
      "doors": [
        10
      ],
      "exits": [
        [
          3,
          "THE HOLLOW WOOD"
        ],
        [
          5,
          "THE CASTLE APPROACH"
        ]
      ],
      "name": "THE BARROW HILLS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 6.599999904632568,
      "town": false
    },
    "area:2:5": {
      "act": 2,
      "doors": [
        11
      ],
      "exits": [
        [
          4,
          "THE BARROW HILLS"
        ]
      ],
      "name": "THE CASTLE APPROACH",
      "passes": [
        "pass3"
      ],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 7.0,
      "town": false
    },
    "area:2:6": {
      "act": 2,
      "doors": [],
      "exits": [
        [
          1,
          "THE BLIGHTED FIELDS"
        ]
      ],
      "name": "THE WITCH'S BOG",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "mistwood",
      "tier": 6.0,
      "town": false
    },
    "area:3:1": {
      "act": 3,
      "doors": [
        12
      ],
      "exits": [
        [
          0,
          "THE LAST ESCAPEMENT"
        ],
        [
          2,
          "THE PISTON FLATS"
        ],
        [
          6,
          "THE SCRAPYARD"
        ]
      ],
      "name": "THE GEARFIELDS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 7.599999904632568,
      "town": false
    },
    "area:3:2": {
      "act": 3,
      "doors": [
        13
      ],
      "exits": [
        [
          1,
          "THE GEARFIELDS"
        ],
        [
          3,
          "THE COGWORKS"
        ]
      ],
      "name": "THE PISTON FLATS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 8.0,
      "town": false
    },
    "area:3:3": {
      "act": 3,
      "doors": [],
      "exits": [
        [
          2,
          "THE PISTON FLATS"
        ],
        [
          4,
          "THE ARCHIVE STACKS"
        ]
      ],
      "name": "THE COGWORKS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 8.399999618530273,
      "town": false
    },
    "area:3:4": {
      "act": 3,
      "doors": [
        14
      ],
      "exits": [
        [
          3,
          "THE COGWORKS"
        ],
        [
          5,
          "THE CLOCKFACE PLAIN"
        ]
      ],
      "name": "THE ARCHIVE STACKS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 8.600000381469727,
      "town": false
    },
    "area:3:5": {
      "act": 3,
      "doors": [
        15
      ],
      "exits": [
        [
          4,
          "THE ARCHIVE STACKS"
        ]
      ],
      "name": "THE CLOCKFACE PLAIN",
      "passes": [
        "pass4"
      ],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 9.0,
      "town": false
    },
    "area:3:6": {
      "act": 3,
      "doors": [],
      "exits": [
        [
          1,
          "THE GEARFIELDS"
        ]
      ],
      "name": "THE SCRAPYARD",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "mechanus",
      "tier": 8.0,
      "town": false
    },
    "area:4:1": {
      "act": 4,
      "doors": [
        16
      ],
      "exits": [
        [
          0,
          "BRINEHOLLOW"
        ],
        [
          2,
          "THE CORAL GARDENS"
        ]
      ],
      "name": "THE KELP SHALLOWS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "deep",
      "tier": 10.0,
      "town": false
    },
    "area:4:2": {
      "act": 4,
      "doors": [
        17
      ],
      "exits": [
        [
          1,
          "THE KELP SHALLOWS"
        ],
        [
          3,
          "THE BONE REEF"
        ],
        [
          6,
          "THE SUNKEN GALLEON"
        ]
      ],
      "name": "THE CORAL GARDENS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "deep",
      "tier": 10.399999618530273,
      "town": false
    },
    "area:4:3": {
      "act": 4,
      "doors": [],
      "exits": [
        [
          2,
          "THE CORAL GARDENS"
        ],
        [
          4,
          "THE TRENCH RIM"
        ]
      ],
      "name": "THE BONE REEF",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "deep",
      "tier": 10.800000190734863,
      "town": false
    },
    "area:4:4": {
      "act": 4,
      "doors": [
        18
      ],
      "exits": [
        [
          3,
          "THE BONE REEF"
        ],
        [
          5,
          "THE ABYSSAL PLAIN"
        ]
      ],
      "name": "THE TRENCH RIM",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "deep",
      "tier": 11.0,
      "town": false
    },
    "area:4:5": {
      "act": 4,
      "doors": [
        19
      ],
      "exits": [
        [
          4,
          "THE TRENCH RIM"
        ]
      ],
      "name": "THE ABYSSAL PLAIN",
      "passes": [
        "pass5"
      ],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "deep",
      "tier": 11.399999618530273,
      "town": false
    },
    "area:4:6": {
      "act": 4,
      "doors": [],
      "exits": [
        [
          2,
          "THE CORAL GARDENS"
        ]
      ],
      "name": "THE SUNKEN GALLEON",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "deep",
      "tier": 10.600000381469727,
      "town": false
    },
    "area:5:1": {
      "act": 5,
      "doors": [
        20
      ],
      "exits": [
        [
          0,
          "WINDWARD ANCHORAGE"
        ],
        [
          2,
          "THE STORMFIELDS"
        ]
      ],
      "name": "THE BROKEN STEPS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "heavens",
      "tier": 12.0,
      "town": false
    },
    "area:5:2": {
      "act": 5,
      "doors": [
        21
      ],
      "exits": [
        [
          1,
          "THE BROKEN STEPS"
        ],
        [
          3,
          "THE FALLEN GARDENS"
        ]
      ],
      "name": "THE STORMFIELDS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "heavens",
      "tier": 12.399999618530273,
      "town": false
    },
    "area:5:3": {
      "act": 5,
      "doors": [],
      "exits": [
        [
          2,
          "THE STORMFIELDS"
        ],
        [
          4,
          "THE HALO ISLES"
        ],
        [
          6,
          "THE DRIFTING ISLES"
        ]
      ],
      "name": "THE FALLEN GARDENS",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "heavens",
      "tier": 12.800000190734863,
      "town": false
    },
    "area:5:4": {
      "act": 5,
      "doors": [
        22
      ],
      "exits": [
        [
          3,
          "THE FALLEN GARDENS"
        ],
        [
          5,
          "THE ZENITH"
        ]
      ],
      "name": "THE HALO ISLES",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "heavens",
      "tier": 13.0,
      "town": false
    },
    "area:5:5": {
      "act": 5,
      "doors": [
        23
      ],
      "exits": [
        [
          4,
          "THE HALO ISLES"
        ]
      ],
      "name": "THE ZENITH",
      "passes": [],
      "shops": [],
      "size": [
        96,
        96
      ],
      "story": null,
      "theme": "heavens",
      "tier": 13.399999618530273,
      "town": false
    },
    "area:5:6": {
      "act": 5,
      "doors": [],
      "exits": [
        [
          3,
          "THE FALLEN GARDENS"
        ]
      ],
      "name": "THE DRIFTING ISLES",
      "passes": [],
      "shops": [],
      "size": [
        64,
        64
      ],
      "story": null,
      "theme": "heavens",
      "tier": 12.600000381469727,
      "town": false
    },
    "deep": {
      "act": 4,
      "doors": [],
      "exits": [
        [
          1,
          "THE KELP SHALLOWS"
        ]
      ],
      "name": "THE SUNKEN REACH",
      "passes": [
        "pass3"
      ],
      "shops": [
        "coral",
        "jeweler4",
        "nessa"
      ],
      "size": [
        112,
        112
      ],
      "story": [
        "ysolde",
        "CAPTAIN YSOLDE MARROW"
      ],
      "theme": "deep",
      "tier": 9.600000381469727,
      "town": true
    },
    "frostmarch": {
      "act": 1,
      "doors": [],
      "exits": [
        [
          1,
          "THE FROZEN SHORE"
        ]
      ],
      "name": "THE FROSTMARCH",
      "passes": [
        "pass0"
      ],
      "shops": [
        "jeweler1",
        "seer",
        "trader"
      ],
      "size": [
        112,
        112
      ],
      "story": [
        "captain",
        "CAPTAIN BRENNA"
      ],
      "theme": "tundra",
      "tier": 3.4000000953674316,
      "town": true
    },
    "heavens": {
      "act": 5,
      "doors": [],
      "exits": [
        [
          1,
          "THE BROKEN STEPS"
        ]
      ],
      "name": "THE SKYREACH",
      "passes": [
        "dock0",
        "pass4"
      ],
      "shops": [
        "aurel",
        "bram",
        "jeweler5"
      ],
      "size": [
        112,
        112
      ],
      "story": [
        "seraphine",
        "SERAPHINE"
      ],
      "theme": "heavens",
      "tier": 12.0,
      "town": true
    },
    "mechanus": {
      "act": 3,
      "doors": [],
      "exits": [
        [
          1,
          "THE GEARFIELDS"
        ]
      ],
      "name": "THE GRINDING FIELDS",
      "passes": [
        "pass2"
      ],
      "shops": [
        "jeweler3",
        "oiler",
        "vesper"
      ],
      "size": [
        112,
        112
      ],
      "story": [
        "tally",
        "TALLY"
      ],
      "theme": "mechanus",
      "tier": 7.199999809265137,
      "town": true
    },
    "mistwood": {
      "act": 2,
      "doors": [],
      "exits": [
        [
          1,
          "THE BLIGHTED FIELDS"
        ]
      ],
      "name": "THE MISTWOOD",
      "passes": [
        "pass1"
      ],
      "shops": [
        "jeweler2",
        "priest",
        "widow"
      ],
      "size": [
        112,
        112
      ],
      "story": [
        "hunter",
        "ABELARD"
      ],
      "theme": "mistwood",
      "tier": 5.199999809265137,
      "town": true
    },
    "overworld": {
      "act": 0,
      "doors": [],
      "exits": [
        [
          1,
          "THE ASHLANDS"
        ]
      ],
      "name": "HOLLOWMERE",
      "passes": [],
      "shops": [
        "healer",
        "jeweler0",
        "merchant"
      ],
      "size": [
        80,
        80
      ],
      "story": [
        "elder",
        "ELDER MAREN"
      ],
      "theme": "overworld",
      "tier": 1.0,
      "town": true
    }
  },
  "monsters": [
    {
      "boss": false,
      "kind": "zombie",
      "name": "ROTTING ZOMBIE",
      "prop": false
    },
    {
      "boss": false,
      "kind": "skeleton",
      "name": "RISEN SKELETON",
      "prop": false
    },
    {
      "boss": false,
      "kind": "wolf",
      "name": "DIRE WOLF",
      "prop": false
    },
    {
      "boss": false,
      "kind": "goblin",
      "name": "GOBLIN",
      "prop": false
    },
    {
      "boss": false,
      "kind": "archer",
      "name": "SKELETON ARCHER",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_bone",
      "name": "THE BONE WARDEN",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_plague",
      "name": "THE PLAGUE WARDEN",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_hex",
      "name": "THE HEX WARDEN",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_ashking",
      "name": "THE ASH KING",
      "prop": false
    },
    {
      "boss": false,
      "kind": "frost_wolf",
      "name": "WINTER WOLF",
      "prop": false
    },
    {
      "boss": false,
      "kind": "raider",
      "name": "NORTHERN RAIDER",
      "prop": false
    },
    {
      "boss": false,
      "kind": "yeti",
      "name": "YETI",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ice_troll",
      "name": "ICE TROLL",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ice_wraith",
      "name": "ICE WRAITH",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_giant",
      "name": "THE FROST GIANT OVERSEER",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_yeti",
      "name": "THE YETI MATRIARCH",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_witch",
      "name": "THE RIME WITCH",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_dragon",
      "name": "VORTHRAX THE RIME WYRM",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ghoul",
      "name": "GHOUL",
      "prop": false
    },
    {
      "boss": false,
      "kind": "werewolf",
      "name": "WEREWOLF",
      "prop": false
    },
    {
      "boss": false,
      "kind": "banshee",
      "name": "BANSHEE",
      "prop": false
    },
    {
      "boss": false,
      "kind": "wisp",
      "name": "WILL-O'-WISP",
      "prop": false
    },
    {
      "boss": false,
      "kind": "cultist",
      "name": "CULTIST",
      "prop": false
    },
    {
      "boss": false,
      "kind": "vbat",
      "name": "VAMPIRE BAT",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_ossric",
      "name": "LORD OSSRIC, THE BONE BARON",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_grimhilde",
      "name": "DUCHESS GRIMHILDE",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_malgrave",
      "name": "SIR MALGRAVE, THE DEATH KNIGHT",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_vardak",
      "name": "COUNT VARDAK",
      "prop": false
    },
    {
      "boss": false,
      "kind": "brass_scarab",
      "name": "BRASS SCARAB",
      "prop": false
    },
    {
      "boss": false,
      "kind": "inquisitor",
      "name": "CENSER AUTOMATON",
      "prop": false
    },
    {
      "boss": false,
      "kind": "gearwraith",
      "name": "GEARWRAITH",
      "prop": false
    },
    {
      "boss": false,
      "kind": "spring_jack",
      "name": "SPRING-HEELED JACK",
      "prop": false
    },
    {
      "boss": false,
      "kind": "boiler_brute",
      "name": "BOILER BRUTE",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ordinal",
      "name": "ORDINAL CUBIT",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ordinal_prism",
      "name": "ORDINAL PRISM",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ordinal_marshal",
      "name": "ORDINAL MARSHAL",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_forgemother",
      "name": "THE FORGEMOTHER",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_cantor",
      "name": "THE CANTOR",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_archivist",
      "name": "THE ARCHIVIST",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_clockmaker",
      "name": "THE CLOCKMAKER",
      "prop": false
    },
    {
      "boss": false,
      "kind": "clock_crow",
      "name": "CLOCKWORK CROW",
      "prop": false
    },
    {
      "boss": false,
      "kind": "crate",
      "name": "CRATE",
      "prop": true
    },
    {
      "boss": false,
      "kind": "barrel",
      "name": "BARREL",
      "prop": true
    },
    {
      "boss": false,
      "kind": "urn",
      "name": "URN",
      "prop": true
    },
    {
      "boss": false,
      "kind": "drowned_sailor",
      "name": "DROWNED SAILOR",
      "prop": false
    },
    {
      "boss": false,
      "kind": "merrow",
      "name": "MERROW SPEARMAN",
      "prop": false
    },
    {
      "boss": false,
      "kind": "anglerlurk",
      "name": "ANGLERLURK",
      "prop": false
    },
    {
      "boss": false,
      "kind": "jelly_drift",
      "name": "JELLY DRIFT",
      "prop": false
    },
    {
      "boss": false,
      "kind": "shellguard",
      "name": "SHELLGUARD",
      "prop": false
    },
    {
      "boss": false,
      "kind": "siren",
      "name": "SIREN",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ink_horror",
      "name": "INK HORROR",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_dregmoor",
      "name": "ADMIRAL DREGMOOR",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_nacre",
      "name": "MOTHER NACRE, THE SIREN QUEEN",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_angler",
      "name": "THE ANGLER MATRIARCH",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_leviathan",
      "name": "THE LEVIATHAN",
      "prop": false
    },
    {
      "boss": false,
      "kind": "fallen_seraph",
      "name": "FALLEN SERAPH",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ophanim",
      "name": "OPHANIM",
      "prop": false
    },
    {
      "boss": false,
      "kind": "storm_drake",
      "name": "STORM DRAKE",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ash_harpy",
      "name": "ASH HARPY",
      "prop": false
    },
    {
      "boss": false,
      "kind": "gilded_sentinel",
      "name": "GILDED SENTINEL",
      "prop": false
    },
    {
      "boss": false,
      "kind": "sun_zealot",
      "name": "SUN-ZEALOT",
      "prop": false
    },
    {
      "boss": false,
      "kind": "thunderbird",
      "name": "THUNDERBIRD",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_vael",
      "name": "SERAPH-COMMANDER VAEL",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_tempest",
      "name": "THE TEMPEST DRAKE",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_ophan",
      "name": "THE OPHAN PRIME",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_solanthos",
      "name": "SOLANTHOS, THE BURNT-OUT SUN",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_wellwitch",
      "name": "THE WELL-WITCH",
      "prop": false
    },
    {
      "boss": false,
      "kind": "hoarder",
      "name": "GOLD-THIEF",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_firewyrm",
      "name": "VAURATH THE EMBER WYRM",
      "prop": false
    },
    {
      "boss": false,
      "kind": "totem",
      "name": "BONE TOTEM",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ash_elemental",
      "name": "ASH ELEMENTAL",
      "prop": false
    },
    {
      "boss": false,
      "kind": "ice_block",
      "name": "BLOCK OF ICE",
      "prop": false
    },
    {
      "boss": true,
      "kind": "boss_hrolf",
      "name": "HROLF ICE-BEARD",
      "prop": false
    }
  ],
  "npcs": [
    {
      "img": "npc_elder",
      "kind": "elder",
      "name": "ELDER MAREN"
    },
    {
      "img": "npc_merchant",
      "kind": "merchant",
      "name": "GERTA"
    },
    {
      "img": "npc_healer",
      "kind": "healer",
      "name": "BROTHER ALDRIC"
    },
    {
      "img": "npc_guard",
      "kind": "guard",
      "name": "CAPTAIN ROLF"
    },
    {
      "img": "npc_villager",
      "kind": "villager0",
      "name": "VILLAGER"
    },
    {
      "img": "npc_villager",
      "kind": "villager1",
      "name": "FARMER"
    },
    {
      "img": "npc_villager",
      "kind": "villager2",
      "name": "VILLAGER"
    },
    {
      "img": "npc_villager",
      "kind": "villager3",
      "name": "FARMER"
    },
    {
      "img": "npc_captain",
      "kind": "captain",
      "name": "CAPTAIN BRENNA"
    },
    {
      "img": "npc_trader",
      "kind": "trader",
      "name": "OLD SIGURD"
    },
    {
      "img": "npc_seer",
      "kind": "seer",
      "name": "MOTHER YLVA"
    },
    {
      "img": "npc_fisher",
      "kind": "fisher0",
      "name": "FISHERMAN"
    },
    {
      "img": "npc_fisher",
      "kind": "fisher1",
      "name": "FISHERMAN"
    },
    {
      "img": "npc_fisher",
      "kind": "fisher2",
      "name": "FISHERWIFE"
    },
    {
      "img": "npc_hunter",
      "kind": "hunter",
      "name": "ABELARD"
    },
    {
      "img": "npc_widow",
      "kind": "widow",
      "name": "WIDOW KASIA"
    },
    {
      "img": "npc_priest",
      "kind": "priest",
      "name": "FATHER LUCIAN"
    },
    {
      "img": "npc_peasant",
      "kind": "peasant0",
      "name": "PEASANT"
    },
    {
      "img": "npc_peasant",
      "kind": "peasant1",
      "name": "PEASANT"
    },
    {
      "img": "npc_peasant",
      "kind": "peasant2",
      "name": "PEASANT"
    },
    {
      "img": "npc_tally",
      "kind": "tally",
      "name": "TALLY"
    },
    {
      "img": "npc_vesper",
      "kind": "vesper",
      "name": "MADAME VESPER"
    },
    {
      "img": "npc_oiler",
      "kind": "oiler",
      "name": "BROTHER PISTON"
    },
    {
      "img": "npc_servant",
      "kind": "servant0",
      "name": "SERVANT"
    },
    {
      "img": "npc_servant",
      "kind": "servant1",
      "name": "SERVANT"
    },
    {
      "img": "npc_servant",
      "kind": "servant2",
      "name": "SERVANT"
    },
    {
      "img": "npc_jeweler0",
      "kind": "jeweler0",
      "name": "MASTER ODO"
    },
    {
      "img": "npc_jeweler1",
      "kind": "jeweler1",
      "name": "INGRID STONEHAND"
    },
    {
      "img": "npc_jeweler2",
      "kind": "jeweler2",
      "name": "SILAS GREAVE"
    },
    {
      "img": "npc_jeweler3",
      "kind": "jeweler3",
      "name": "THE LAPIDARY"
    },
    {
      "img": "npc_ysolde",
      "kind": "ysolde",
      "name": "CAPTAIN YSOLDE MARROW"
    },
    {
      "img": "npc_nessa",
      "kind": "nessa",
      "name": "NESSA THE PEARL-DIVER"
    },
    {
      "img": "npc_coral",
      "kind": "coral",
      "name": "BROTHER CORAL"
    },
    {
      "img": "npc_diver",
      "kind": "diver0",
      "name": "DIVER"
    },
    {
      "img": "npc_diver",
      "kind": "diver1",
      "name": "DIVER"
    },
    {
      "img": "npc_diver",
      "kind": "diver2",
      "name": "DIVER"
    },
    {
      "img": "npc_jeweler4",
      "kind": "jeweler4",
      "name": "THE PEARL-SETTER"
    },
    {
      "img": "npc_seraphine",
      "kind": "seraphine",
      "name": "SERAPHINE"
    },
    {
      "img": "npc_bram",
      "kind": "bram",
      "name": "QUARTERMASTER BRAM"
    },
    {
      "img": "npc_aurel",
      "kind": "aurel",
      "name": "SISTER AUREL"
    },
    {
      "img": "npc_deckhand",
      "kind": "deckhand0",
      "name": "DECKHAND"
    },
    {
      "img": "npc_deckhand",
      "kind": "deckhand1",
      "name": "DECKHAND"
    },
    {
      "img": "npc_deckhand",
      "kind": "deckhand2",
      "name": "DECKHAND"
    },
    {
      "img": "npc_jeweler5",
      "kind": "jeweler5",
      "name": "THE GILDER"
    }
  ],
  "props": [
    {
      "h": 1,
      "kind": "tree_oak",
      "w": 1
    },
    {
      "h": 1,
      "kind": "tree_pine",
      "w": 1
    },
    {
      "h": 1,
      "kind": "tree_dead",
      "w": 1
    },
    {
      "h": 1,
      "kind": "rock1",
      "w": 1
    },
    {
      "h": 1,
      "kind": "bush1",
      "w": 1
    },
    {
      "h": 4,
      "kind": "house1",
      "w": 4
    },
    {
      "h": 4,
      "kind": "house2",
      "w": 4
    },
    {
      "h": 2,
      "kind": "tent1",
      "w": 3
    },
    {
      "h": 1,
      "kind": "campfire",
      "w": 1
    },
    {
      "h": 1,
      "kind": "well",
      "w": 1
    },
    {
      "h": 3,
      "kind": "ent_crypt",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_warrens",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_catacombs",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_sanctum",
      "w": 3
    },
    {
      "h": 1,
      "kind": "tree_snowpine",
      "w": 1
    },
    {
      "h": 1,
      "kind": "tree_snowdead",
      "w": 1
    },
    {
      "h": 1,
      "kind": "rock_snow",
      "w": 1
    },
    {
      "h": 1,
      "kind": "ice_crystal",
      "w": 1
    },
    {
      "h": 4,
      "kind": "longhouse1",
      "w": 5
    },
    {
      "h": 4,
      "kind": "longhouse2",
      "w": 4
    },
    {
      "h": 2,
      "kind": "stall_furs",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_mines",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_caves",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_temple",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_glacier",
      "w": 4
    },
    {
      "h": 2,
      "kind": "pass_gate",
      "w": 3
    },
    {
      "h": 1,
      "kind": "tree_twisted",
      "w": 1
    },
    {
      "h": 1,
      "kind": "tree_mistpine",
      "w": 1
    },
    {
      "h": 1,
      "kind": "glow_shrooms",
      "w": 1
    },
    {
      "h": 1,
      "kind": "gravestone",
      "w": 1
    },
    {
      "h": 4,
      "kind": "cottage_mist",
      "w": 4
    },
    {
      "h": 4,
      "kind": "cottage_mist2",
      "w": 4
    },
    {
      "h": 1,
      "kind": "gallows",
      "w": 1
    },
    {
      "h": 2,
      "kind": "merchant_cart",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_chapel",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_gallows",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_barrow",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_castle",
      "w": 4
    },
    {
      "h": 3,
      "kind": "pass_mist",
      "w": 2
    },
    {
      "h": 1,
      "kind": "gear_tower",
      "w": 1
    },
    {
      "h": 2,
      "kind": "steam_pipes",
      "w": 1
    },
    {
      "h": 1,
      "kind": "steam_vent",
      "w": 1
    },
    {
      "h": 1,
      "kind": "gas_lamp",
      "w": 1
    },
    {
      "h": 1,
      "kind": "cog_pile",
      "w": 1
    },
    {
      "h": 4,
      "kind": "workshop1",
      "w": 4
    },
    {
      "h": 4,
      "kind": "workshop2",
      "w": 4
    },
    {
      "h": 2,
      "kind": "clock_tower",
      "w": 2
    },
    {
      "h": 1,
      "kind": "pendulum",
      "w": 1
    },
    {
      "h": 3,
      "kind": "ent_foundry",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_choir",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_archive",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_clock",
      "w": 4
    },
    {
      "h": 2,
      "kind": "gear_gate",
      "w": 3
    },
    {
      "h": 1,
      "kind": "kelp1",
      "w": 1
    },
    {
      "h": 2,
      "kind": "coral1",
      "w": 2
    },
    {
      "h": 2,
      "kind": "coral2",
      "w": 1
    },
    {
      "h": 2,
      "kind": "wreck_hull",
      "w": 3
    },
    {
      "h": 2,
      "kind": "whale_bones",
      "w": 3
    },
    {
      "h": 4,
      "kind": "stilt_house1",
      "w": 4
    },
    {
      "h": 4,
      "kind": "stilt_house2",
      "w": 4
    },
    {
      "h": 1,
      "kind": "shell_lamp",
      "w": 1
    },
    {
      "h": 1,
      "kind": "anchor_rock",
      "w": 1
    },
    {
      "h": 2,
      "kind": "diving_bell",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_wreck",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_cathedral",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_trench",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_drowned",
      "w": 4
    },
    {
      "h": 1,
      "kind": "angel_statue",
      "w": 1
    },
    {
      "h": 2,
      "kind": "halo_arch",
      "w": 2
    },
    {
      "h": 1,
      "kind": "sky_lamp",
      "w": 1
    },
    {
      "h": 1,
      "kind": "cloud_tree",
      "w": 1
    },
    {
      "h": 1,
      "kind": "marble_ruin",
      "w": 1
    },
    {
      "h": 4,
      "kind": "sky_house1",
      "w": 4
    },
    {
      "h": 4,
      "kind": "sky_house2",
      "w": 4
    },
    {
      "h": 2,
      "kind": "airship_dock",
      "w": 3
    },
    {
      "h": 2,
      "kind": "light_stair",
      "w": 2
    },
    {
      "h": 3,
      "kind": "ent_brokenchoir",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_spire",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_wheel",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_zenith",
      "w": 4
    },
    {
      "h": 3,
      "kind": "ent_charnel",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_wyrm",
      "w": 3
    },
    {
      "h": 3,
      "kind": "ent_longship",
      "w": 3
    },
    {
      "h": 1,
      "kind": "shrine_frost",
      "w": 1
    },
    {
      "h": 1,
      "kind": "shrine_ash",
      "w": 1
    }
  ],
  "slugs": {
    "area:0:1": "the_ashlands",
    "area:0:2": "the_barrow_fields",
    "area:0:3": "the_rotwood",
    "area:0:4": "the_cinder_hills",
    "area:0:5": "the_cinder_waste",
    "area:0:6": "the_ashen_steppe",
    "area:0:7": "shepherds_vale",
    "area:0:8": "skrats_gulch",
    "area:0:9": "emberpeak_pass",
    "area:1:1": "the_frozen_shore",
    "area:1:2": "the_howling_tundra",
    "area:1:3": "the_rime_woods",
    "area:1:4": "the_white_waste",
    "area:1:5": "the_glaciers_edge",
    "area:1:6": "the_raiders_fjord",
    "area:2:1": "the_blighted_fields",
    "area:2:2": "the_gallows_moor",
    "area:2:3": "the_hollow_wood",
    "area:2:4": "the_barrow_hills",
    "area:2:5": "the_castle_approach",
    "area:2:6": "the_witchs_bog",
    "area:3:1": "the_gearfields",
    "area:3:2": "the_piston_flats",
    "area:3:3": "the_cogworks",
    "area:3:4": "the_archive_stacks",
    "area:3:5": "the_clockface_plain",
    "area:3:6": "the_scrapyard",
    "area:4:1": "the_kelp_shallows",
    "area:4:2": "the_coral_gardens",
    "area:4:3": "the_bone_reef",
    "area:4:4": "the_trench_rim",
    "area:4:5": "the_abyssal_plain",
    "area:4:6": "the_sunken_galleon",
    "area:5:1": "the_broken_steps",
    "area:5:2": "the_stormfields",
    "area:5:3": "the_fallen_gardens",
    "area:5:4": "the_halo_isles",
    "area:5:5": "the_zenith",
    "area:5:6": "the_drifting_isles"
  },
  "themes": [
    {
      "name": "overworld",
      "open": true,
      "sky": false
    },
    {
      "name": "crypt",
      "open": false,
      "sky": false
    },
    {
      "name": "warrens",
      "open": false,
      "sky": false
    },
    {
      "name": "catacombs",
      "open": false,
      "sky": false
    },
    {
      "name": "sanctum",
      "open": false,
      "sky": false
    },
    {
      "name": "tundra",
      "open": true,
      "sky": false
    },
    {
      "name": "mines",
      "open": false,
      "sky": false
    },
    {
      "name": "icecaves",
      "open": false,
      "sky": false
    },
    {
      "name": "rime",
      "open": false,
      "sky": false
    },
    {
      "name": "glacier",
      "open": false,
      "sky": false
    },
    {
      "name": "mistwood",
      "open": true,
      "sky": false
    },
    {
      "name": "chapel",
      "open": false,
      "sky": false
    },
    {
      "name": "gallows",
      "open": false,
      "sky": false
    },
    {
      "name": "barrow",
      "open": false,
      "sky": false
    },
    {
      "name": "castle",
      "open": false,
      "sky": false
    },
    {
      "name": "mechanus",
      "open": true,
      "sky": false
    },
    {
      "name": "foundry",
      "open": false,
      "sky": false
    },
    {
      "name": "choir",
      "open": false,
      "sky": false
    },
    {
      "name": "archive",
      "open": false,
      "sky": false
    },
    {
      "name": "clock",
      "open": false,
      "sky": false
    },
    {
      "name": "deep",
      "open": true,
      "sky": false
    },
    {
      "name": "wreck",
      "open": false,
      "sky": false
    },
    {
      "name": "reef",
      "open": false,
      "sky": false
    },
    {
      "name": "trench",
      "open": false,
      "sky": false
    },
    {
      "name": "drowned",
      "open": false,
      "sky": false
    },
    {
      "name": "heavens",
      "open": true,
      "sky": true
    },
    {
      "name": "seraph",
      "open": false,
      "sky": true
    },
    {
      "name": "spire",
      "open": false,
      "sky": true
    },
    {
      "name": "wheel",
      "open": false,
      "sky": true
    },
    {
      "name": "zenith",
      "open": false,
      "sky": true
    }
  ]
};
